// Generated by gencpp from file lane_detector/Lane.msg
// DO NOT EDIT!


#ifndef LANE_DETECTOR_MESSAGE_LANE_H
#define LANE_DETECTOR_MESSAGE_LANE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>
#include <geometry_msgs/Point32.h>
#include <geometry_msgs/Point32.h>
#include <geometry_msgs/Point32.h>

namespace lane_detector
{
template <class ContainerAllocator>
struct Lane_
{
  typedef Lane_<ContainerAllocator> Type;

  Lane_()
    : header()
    , left_line()
    , right_line()
    , guide_line()  {
    }
  Lane_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , left_line(_alloc)
    , right_line(_alloc)
    , guide_line(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef std::vector< ::geometry_msgs::Point32_<ContainerAllocator> , typename ContainerAllocator::template rebind< ::geometry_msgs::Point32_<ContainerAllocator> >::other >  _left_line_type;
  _left_line_type left_line;

   typedef std::vector< ::geometry_msgs::Point32_<ContainerAllocator> , typename ContainerAllocator::template rebind< ::geometry_msgs::Point32_<ContainerAllocator> >::other >  _right_line_type;
  _right_line_type right_line;

   typedef std::vector< ::geometry_msgs::Point32_<ContainerAllocator> , typename ContainerAllocator::template rebind< ::geometry_msgs::Point32_<ContainerAllocator> >::other >  _guide_line_type;
  _guide_line_type guide_line;




  typedef boost::shared_ptr< ::lane_detector::Lane_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::lane_detector::Lane_<ContainerAllocator> const> ConstPtr;

}; // struct Lane_

typedef ::lane_detector::Lane_<std::allocator<void> > Lane;

typedef boost::shared_ptr< ::lane_detector::Lane > LanePtr;
typedef boost::shared_ptr< ::lane_detector::Lane const> LaneConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::lane_detector::Lane_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::lane_detector::Lane_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace lane_detector

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': True}
// {'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg'], 'lane_detector': ['/home/sebastian/catkin_ws/src/lane_detector/msg'], 'geometry_msgs': ['/opt/ros/indigo/share/geometry_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::lane_detector::Lane_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::lane_detector::Lane_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::lane_detector::Lane_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::lane_detector::Lane_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::lane_detector::Lane_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::lane_detector::Lane_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::lane_detector::Lane_<ContainerAllocator> >
{
  static const char* value()
  {
    return "c90a7e3d5672c12e51f2e3f5f1598108";
  }

  static const char* value(const ::lane_detector::Lane_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xc90a7e3d5672c12eULL;
  static const uint64_t static_value2 = 0x51f2e3f5f1598108ULL;
};

template<class ContainerAllocator>
struct DataType< ::lane_detector::Lane_<ContainerAllocator> >
{
  static const char* value()
  {
    return "lane_detector/Lane";
  }

  static const char* value(const ::lane_detector::Lane_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::lane_detector::Lane_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n\
geometry_msgs/Point32[] left_line\n\
geometry_msgs/Point32[] right_line\n\
geometry_msgs/Point32[] guide_line\n\
\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n\
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Point32\n\
# This contains the position of a point in free space(with 32 bits of precision).\n\
# It is recommeded to use Point wherever possible instead of Point32.  \n\
# \n\
# This recommendation is to promote interoperability.  \n\
#\n\
# This message is designed to take up less space when sending\n\
# lots of points at once, as in the case of a PointCloud.  \n\
\n\
float32 x\n\
float32 y\n\
float32 z\n\
";
  }

  static const char* value(const ::lane_detector::Lane_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::lane_detector::Lane_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.left_line);
      stream.next(m.right_line);
      stream.next(m.guide_line);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Lane_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::lane_detector::Lane_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::lane_detector::Lane_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "left_line[]" << std::endl;
    for (size_t i = 0; i < v.left_line.size(); ++i)
    {
      s << indent << "  left_line[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::geometry_msgs::Point32_<ContainerAllocator> >::stream(s, indent + "    ", v.left_line[i]);
    }
    s << indent << "right_line[]" << std::endl;
    for (size_t i = 0; i < v.right_line.size(); ++i)
    {
      s << indent << "  right_line[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::geometry_msgs::Point32_<ContainerAllocator> >::stream(s, indent + "    ", v.right_line[i]);
    }
    s << indent << "guide_line[]" << std::endl;
    for (size_t i = 0; i < v.guide_line.size(); ++i)
    {
      s << indent << "  guide_line[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::geometry_msgs::Point32_<ContainerAllocator> >::stream(s, indent + "    ", v.guide_line[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // LANE_DETECTOR_MESSAGE_LANE_H
