// Generated by gencpp from file swri_profiler_msgs/ProfileIndex.msg
// DO NOT EDIT!


#ifndef SWRI_PROFILER_MSGS_MESSAGE_PROFILEINDEX_H
#define SWRI_PROFILER_MSGS_MESSAGE_PROFILEINDEX_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace swri_profiler_msgs
{
template <class ContainerAllocator>
struct ProfileIndex_
{
  typedef ProfileIndex_<ContainerAllocator> Type;

  ProfileIndex_()
    : key(0)
    , label()  {
    }
  ProfileIndex_(const ContainerAllocator& _alloc)
    : key(0)
    , label(_alloc)  {
  (void)_alloc;
    }



   typedef uint32_t _key_type;
  _key_type key;

   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _label_type;
  _label_type label;




  typedef boost::shared_ptr< ::swri_profiler_msgs::ProfileIndex_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::swri_profiler_msgs::ProfileIndex_<ContainerAllocator> const> ConstPtr;

}; // struct ProfileIndex_

typedef ::swri_profiler_msgs::ProfileIndex_<std::allocator<void> > ProfileIndex;

typedef boost::shared_ptr< ::swri_profiler_msgs::ProfileIndex > ProfileIndexPtr;
typedef boost::shared_ptr< ::swri_profiler_msgs::ProfileIndex const> ProfileIndexConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::swri_profiler_msgs::ProfileIndex_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::swri_profiler_msgs::ProfileIndex_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace swri_profiler_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg'], 'swri_profiler_msgs': ['/home/sebastian/catkin_ws/src/swri_profiler_msgs/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::swri_profiler_msgs::ProfileIndex_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::swri_profiler_msgs::ProfileIndex_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::swri_profiler_msgs::ProfileIndex_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::swri_profiler_msgs::ProfileIndex_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::swri_profiler_msgs::ProfileIndex_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::swri_profiler_msgs::ProfileIndex_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::swri_profiler_msgs::ProfileIndex_<ContainerAllocator> >
{
  static const char* value()
  {
    return "c30eff6f5a4da1cc6130f42d6fb3061a";
  }

  static const char* value(const ::swri_profiler_msgs::ProfileIndex_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xc30eff6f5a4da1ccULL;
  static const uint64_t static_value2 = 0x6130f42d6fb3061aULL;
};

template<class ContainerAllocator>
struct DataType< ::swri_profiler_msgs::ProfileIndex_<ContainerAllocator> >
{
  static const char* value()
  {
    return "swri_profiler_msgs/ProfileIndex";
  }

  static const char* value(const ::swri_profiler_msgs::ProfileIndex_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::swri_profiler_msgs::ProfileIndex_<ContainerAllocator> >
{
  static const char* value()
  {
    return "uint32 key\n\
string label\n\
";
  }

  static const char* value(const ::swri_profiler_msgs::ProfileIndex_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::swri_profiler_msgs::ProfileIndex_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.key);
      stream.next(m.label);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ProfileIndex_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::swri_profiler_msgs::ProfileIndex_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::swri_profiler_msgs::ProfileIndex_<ContainerAllocator>& v)
  {
    s << indent << "key: ";
    Printer<uint32_t>::stream(s, indent + "  ", v.key);
    s << indent << "label: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.label);
  }
};

} // namespace message_operations
} // namespace ros

#endif // SWRI_PROFILER_MSGS_MESSAGE_PROFILEINDEX_H
