// Generated by gencpp from file swri_profiler_msgs/ProfileIndexArray.msg
// DO NOT EDIT!


#ifndef SWRI_PROFILER_MSGS_MESSAGE_PROFILEINDEXARRAY_H
#define SWRI_PROFILER_MSGS_MESSAGE_PROFILEINDEXARRAY_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>
#include <swri_profiler_msgs/ProfileIndex.h>

namespace swri_profiler_msgs
{
template <class ContainerAllocator>
struct ProfileIndexArray_
{
  typedef ProfileIndexArray_<ContainerAllocator> Type;

  ProfileIndexArray_()
    : header()
    , data()  {
    }
  ProfileIndexArray_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , data(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef std::vector< ::swri_profiler_msgs::ProfileIndex_<ContainerAllocator> , typename ContainerAllocator::template rebind< ::swri_profiler_msgs::ProfileIndex_<ContainerAllocator> >::other >  _data_type;
  _data_type data;




  typedef boost::shared_ptr< ::swri_profiler_msgs::ProfileIndexArray_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::swri_profiler_msgs::ProfileIndexArray_<ContainerAllocator> const> ConstPtr;

}; // struct ProfileIndexArray_

typedef ::swri_profiler_msgs::ProfileIndexArray_<std::allocator<void> > ProfileIndexArray;

typedef boost::shared_ptr< ::swri_profiler_msgs::ProfileIndexArray > ProfileIndexArrayPtr;
typedef boost::shared_ptr< ::swri_profiler_msgs::ProfileIndexArray const> ProfileIndexArrayConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::swri_profiler_msgs::ProfileIndexArray_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::swri_profiler_msgs::ProfileIndexArray_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace swri_profiler_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': True}
// {'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg'], 'swri_profiler_msgs': ['/home/sebastian/catkin_ws/src/swri_profiler_msgs/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::swri_profiler_msgs::ProfileIndexArray_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::swri_profiler_msgs::ProfileIndexArray_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::swri_profiler_msgs::ProfileIndexArray_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::swri_profiler_msgs::ProfileIndexArray_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::swri_profiler_msgs::ProfileIndexArray_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::swri_profiler_msgs::ProfileIndexArray_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::swri_profiler_msgs::ProfileIndexArray_<ContainerAllocator> >
{
  static const char* value()
  {
    return "2e5edcc7a1e661bf08900a118f6c8d32";
  }

  static const char* value(const ::swri_profiler_msgs::ProfileIndexArray_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x2e5edcc7a1e661bfULL;
  static const uint64_t static_value2 = 0x08900a118f6c8d32ULL;
};

template<class ContainerAllocator>
struct DataType< ::swri_profiler_msgs::ProfileIndexArray_<ContainerAllocator> >
{
  static const char* value()
  {
    return "swri_profiler_msgs/ProfileIndexArray";
  }

  static const char* value(const ::swri_profiler_msgs::ProfileIndexArray_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::swri_profiler_msgs::ProfileIndexArray_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n\
ProfileIndex[] data\n\
\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n\
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
\n\
================================================================================\n\
MSG: swri_profiler_msgs/ProfileIndex\n\
uint32 key\n\
string label\n\
";
  }

  static const char* value(const ::swri_profiler_msgs::ProfileIndexArray_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::swri_profiler_msgs::ProfileIndexArray_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.data);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ProfileIndexArray_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::swri_profiler_msgs::ProfileIndexArray_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::swri_profiler_msgs::ProfileIndexArray_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "data[]" << std::endl;
    for (size_t i = 0; i < v.data.size(); ++i)
    {
      s << indent << "  data[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::swri_profiler_msgs::ProfileIndex_<ContainerAllocator> >::stream(s, indent + "    ", v.data[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // SWRI_PROFILER_MSGS_MESSAGE_PROFILEINDEXARRAY_H
