// Generated by gencpp from file automap/automap_ctrl_msg.msg
// DO NOT EDIT!


#ifndef AUTOMAP_MESSAGE_AUTOMAP_CTRL_MSG_H
#define AUTOMAP_MESSAGE_AUTOMAP_CTRL_MSG_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace automap
{
template <class ContainerAllocator>
struct automap_ctrl_msg_
{
  typedef automap_ctrl_msg_<ContainerAllocator> Type;

  automap_ctrl_msg_()
    : header()
    , control_On(false)
    , detection_On(false)
    , NBV_On(false)  {
    }
  automap_ctrl_msg_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , control_On(false)
    , detection_On(false)
    , NBV_On(false)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef uint8_t _control_On_type;
  _control_On_type control_On;

   typedef uint8_t _detection_On_type;
  _detection_On_type detection_On;

   typedef uint8_t _NBV_On_type;
  _NBV_On_type NBV_On;




  typedef boost::shared_ptr< ::automap::automap_ctrl_msg_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::automap::automap_ctrl_msg_<ContainerAllocator> const> ConstPtr;

}; // struct automap_ctrl_msg_

typedef ::automap::automap_ctrl_msg_<std::allocator<void> > automap_ctrl_msg;

typedef boost::shared_ptr< ::automap::automap_ctrl_msg > automap_ctrl_msgPtr;
typedef boost::shared_ptr< ::automap::automap_ctrl_msg const> automap_ctrl_msgConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::automap::automap_ctrl_msg_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::automap::automap_ctrl_msg_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace automap

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': True}
// {'automap': ['/home/sebastian/catkin_ws/src/automap/msg'], 'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::automap::automap_ctrl_msg_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::automap::automap_ctrl_msg_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::automap::automap_ctrl_msg_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::automap::automap_ctrl_msg_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::automap::automap_ctrl_msg_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::automap::automap_ctrl_msg_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::automap::automap_ctrl_msg_<ContainerAllocator> >
{
  static const char* value()
  {
    return "d81dbd131e3b6b8fc12fb25418d8b7d8";
  }

  static const char* value(const ::automap::automap_ctrl_msg_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xd81dbd131e3b6b8fULL;
  static const uint64_t static_value2 = 0xc12fb25418d8b7d8ULL;
};

template<class ContainerAllocator>
struct DataType< ::automap::automap_ctrl_msg_<ContainerAllocator> >
{
  static const char* value()
  {
    return "automap/automap_ctrl_msg";
  }

  static const char* value(const ::automap::automap_ctrl_msg_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::automap::automap_ctrl_msg_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n\
bool control_On\n\
bool detection_On\n\
bool NBV_On\n\
\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n\
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
";
  }

  static const char* value(const ::automap::automap_ctrl_msg_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::automap::automap_ctrl_msg_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.control_On);
      stream.next(m.detection_On);
      stream.next(m.NBV_On);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct automap_ctrl_msg_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::automap::automap_ctrl_msg_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::automap::automap_ctrl_msg_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "control_On: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.control_On);
    s << indent << "detection_On: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.detection_On);
    s << indent << "NBV_On: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.NBV_On);
  }
};

} // namespace message_operations
} // namespace ros

#endif // AUTOMAP_MESSAGE_AUTOMAP_CTRL_MSG_H
