TebLocalPlannerROS:
  max_vel_x: 0.4
  max_vel_theta: 0.3
  max_vel_x_backwards: 0.4
  wheelbase: 0.25
  cmd_angle_instead_rotvel: true
  footprint_model/type: polygon
  footprint_model/vertices: [ [0.23, -0.165], [-0.23, -0.165], [-0.23, 0.165], [0.23, 0.165] ]
  xy_goal_tolerance: 0.5
  yaw_goal_tolerance: 0.5
  min_turning_radius: 0.82
