//#line 2 "/opt/ros/indigo/share/dynamic_reconfigure/cmake/../templates/ConfigType.h.template"
// *********************************************************
// 
// File autogenerated for the simulation package 
// by the dynamic_reconfigure package.
// Please do not edit.
// 
// ********************************************************/

#ifndef __simulation__RANGESENSORCONFIG_H__
#define __simulation__RANGESENSORCONFIG_H__

#include <dynamic_reconfigure/config_tools.h>
#include <limits>
#include <ros/node_handle.h>
#include <dynamic_reconfigure/ConfigDescription.h>
#include <dynamic_reconfigure/ParamDescription.h>
#include <dynamic_reconfigure/Group.h>
#include <dynamic_reconfigure/config_init_mutex.h>
#include <boost/any.hpp>

namespace simulation
{
  class RangeSensorConfigStatics;
  
  class RangeSensorConfig
  {
  public:
    class AbstractParamDescription : public dynamic_reconfigure::ParamDescription
    {
    public:
      AbstractParamDescription(std::string n, std::string t, uint32_t l, 
          std::string d, std::string e)
      {
        name = n;
        type = t;
        level = l;
        description = d;
        edit_method = e;
      }
      
      virtual void clamp(RangeSensorConfig &config, const RangeSensorConfig &max, const RangeSensorConfig &min) const = 0;
      virtual void calcLevel(uint32_t &level, const RangeSensorConfig &config1, const RangeSensorConfig &config2) const = 0;
      virtual void fromServer(const ros::NodeHandle &nh, RangeSensorConfig &config) const = 0;
      virtual void toServer(const ros::NodeHandle &nh, const RangeSensorConfig &config) const = 0;
      virtual bool fromMessage(const dynamic_reconfigure::Config &msg, RangeSensorConfig &config) const = 0;
      virtual void toMessage(dynamic_reconfigure::Config &msg, const RangeSensorConfig &config) const = 0;
      virtual void getValue(const RangeSensorConfig &config, boost::any &val) const = 0;
    };

    typedef boost::shared_ptr<AbstractParamDescription> AbstractParamDescriptionPtr;
    typedef boost::shared_ptr<const AbstractParamDescription> AbstractParamDescriptionConstPtr;
    
    template <class T>
    class ParamDescription : public AbstractParamDescription
    {
    public:
      ParamDescription(std::string name, std::string type, uint32_t level, 
          std::string description, std::string edit_method, T RangeSensorConfig::* f) :
        AbstractParamDescription(name, type, level, description, edit_method),
        field(f)
      {}

      T (RangeSensorConfig::* field);

      virtual void clamp(RangeSensorConfig &config, const RangeSensorConfig &max, const RangeSensorConfig &min) const
      {
        if (config.*field > max.*field)
          config.*field = max.*field;
        
        if (config.*field < min.*field)
          config.*field = min.*field;
      }

      virtual void calcLevel(uint32_t &comb_level, const RangeSensorConfig &config1, const RangeSensorConfig &config2) const
      {
        if (config1.*field != config2.*field)
          comb_level |= level;
      }

      virtual void fromServer(const ros::NodeHandle &nh, RangeSensorConfig &config) const
      {
        nh.getParam(name, config.*field);
      }

      virtual void toServer(const ros::NodeHandle &nh, const RangeSensorConfig &config) const
      {
        nh.setParam(name, config.*field);
      }

      virtual bool fromMessage(const dynamic_reconfigure::Config &msg, RangeSensorConfig &config) const
      {
        return dynamic_reconfigure::ConfigTools::getParameter(msg, name, config.*field);
      }

      virtual void toMessage(dynamic_reconfigure::Config &msg, const RangeSensorConfig &config) const
      {
        dynamic_reconfigure::ConfigTools::appendParameter(msg, name, config.*field);
      }

      virtual void getValue(const RangeSensorConfig &config, boost::any &val) const
      {
        val = config.*field;
      }
    };

    class AbstractGroupDescription : public dynamic_reconfigure::Group
    {
      public:
      AbstractGroupDescription(std::string n, std::string t, int p, int i, bool s)
      {
        name = n;
        type = t;
        parent = p;
        state = s;
        id = i;
      }

      std::vector<AbstractParamDescriptionConstPtr> abstract_parameters;
      bool state;

      virtual void toMessage(dynamic_reconfigure::Config &msg, const boost::any &config) const = 0;
      virtual bool fromMessage(const dynamic_reconfigure::Config &msg, boost::any &config) const =0;
      virtual void updateParams(boost::any &cfg, RangeSensorConfig &top) const= 0;
      virtual void setInitialState(boost::any &cfg) const = 0;


      void convertParams()
      {
        for(std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = abstract_parameters.begin(); i != abstract_parameters.end(); ++i)
        {
          parameters.push_back(dynamic_reconfigure::ParamDescription(**i));
        }
      }
    };

    typedef boost::shared_ptr<AbstractGroupDescription> AbstractGroupDescriptionPtr;
    typedef boost::shared_ptr<const AbstractGroupDescription> AbstractGroupDescriptionConstPtr;

    template<class T, class PT>
    class GroupDescription : public AbstractGroupDescription
    {
    public:
      GroupDescription(std::string name, std::string type, int parent, int id, bool s, T PT::* f) : AbstractGroupDescription(name, type, parent, id, s), field(f)
      {
      }

      GroupDescription(const GroupDescription<T, PT>& g): AbstractGroupDescription(g.name, g.type, g.parent, g.id, g.state), field(g.field), groups(g.groups)
      {
        parameters = g.parameters;
        abstract_parameters = g.abstract_parameters;
      }

      virtual bool fromMessage(const dynamic_reconfigure::Config &msg, boost::any &cfg) const
      {
        PT* config = boost::any_cast<PT*>(cfg);
        if(!dynamic_reconfigure::ConfigTools::getGroupState(msg, name, (*config).*field))
          return false;

        for(std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = groups.begin(); i != groups.end(); ++i)
        {
          boost::any n = &((*config).*field);
          if(!(*i)->fromMessage(msg, n))
            return false;
        }

        return true;
      }

      virtual void setInitialState(boost::any &cfg) const
      {
        PT* config = boost::any_cast<PT*>(cfg);
        T* group = &((*config).*field);
        group->state = state;

        for(std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = groups.begin(); i != groups.end(); ++i)
        {
          boost::any n = boost::any(&((*config).*field));
          (*i)->setInitialState(n);
        }

      }

      virtual void updateParams(boost::any &cfg, RangeSensorConfig &top) const
      {
        PT* config = boost::any_cast<PT*>(cfg);

        T* f = &((*config).*field);
        f->setParams(top, abstract_parameters);

        for(std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = groups.begin(); i != groups.end(); ++i)
        {
          boost::any n = &((*config).*field);
          (*i)->updateParams(n, top);
        }
      }

      virtual void toMessage(dynamic_reconfigure::Config &msg, const boost::any &cfg) const
      {
        const PT config = boost::any_cast<PT>(cfg);
        dynamic_reconfigure::ConfigTools::appendGroup<T>(msg, name, id, parent, config.*field);

        for(std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = groups.begin(); i != groups.end(); ++i)
        {
          (*i)->toMessage(msg, config.*field);
        }
      }

      T (PT::* field);
      std::vector<RangeSensorConfig::AbstractGroupDescriptionConstPtr> groups;
    };
    
class DEFAULT
{
  public:
    DEFAULT()
    {
      state = true;
      name = "Default";
    }

    void setParams(RangeSensorConfig &config, const std::vector<AbstractParamDescriptionConstPtr> params)
    {
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator _i = params.begin(); _i != params.end(); ++_i)
      {
        boost::any val;
        (*_i)->getValue(config, val);

        if("laser_obstacle_color"==(*_i)->name){laser_obstacle_color = boost::any_cast<int>(val);}
        if("laser_max_sensor_distance"==(*_i)->name){laser_max_sensor_distance = boost::any_cast<double>(val);}
        if("laser_min_sensor_distance"==(*_i)->name){laser_min_sensor_distance = boost::any_cast<double>(val);}
        if("laser_field_of_view"==(*_i)->name){laser_field_of_view = boost::any_cast<double>(val);}
        if("laser_angular_resolution"==(*_i)->name){laser_angular_resolution = boost::any_cast<double>(val);}
        if("us_obstacle_color"==(*_i)->name){us_obstacle_color = boost::any_cast<int>(val);}
        if("us_max_sensor_distance"==(*_i)->name){us_max_sensor_distance = boost::any_cast<double>(val);}
        if("us_min_sensor_distance"==(*_i)->name){us_min_sensor_distance = boost::any_cast<double>(val);}
        if("us_field_of_view"==(*_i)->name){us_field_of_view = boost::any_cast<double>(val);}
        if("us_angular_resolution"==(*_i)->name){us_angular_resolution = boost::any_cast<double>(val);}
      }
    }

    int laser_obstacle_color;
double laser_max_sensor_distance;
double laser_min_sensor_distance;
double laser_field_of_view;
double laser_angular_resolution;
int us_obstacle_color;
double us_max_sensor_distance;
double us_min_sensor_distance;
double us_field_of_view;
double us_angular_resolution;

    bool state;
    std::string name;

    
}groups;



//#line 280 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      int laser_obstacle_color;
//#line 280 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double laser_max_sensor_distance;
//#line 280 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double laser_min_sensor_distance;
//#line 280 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double laser_field_of_view;
//#line 280 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double laser_angular_resolution;
//#line 280 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      int us_obstacle_color;
//#line 280 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double us_max_sensor_distance;
//#line 280 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double us_min_sensor_distance;
//#line 280 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double us_field_of_view;
//#line 280 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double us_angular_resolution;
//#line 218 "/opt/ros/indigo/share/dynamic_reconfigure/cmake/../templates/ConfigType.h.template"

    bool __fromMessage__(dynamic_reconfigure::Config &msg)
    {
      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      const std::vector<AbstractGroupDescriptionConstPtr> &__group_descriptions__ = __getGroupDescriptions__();

      int count = 0;
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); ++i)
        if ((*i)->fromMessage(msg, *this))
          count++;

      for (std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = __group_descriptions__.begin(); i != __group_descriptions__.end(); i ++)
      {
        if ((*i)->id == 0)
        {
          boost::any n = boost::any(this);
          (*i)->updateParams(n, *this);
          (*i)->fromMessage(msg, n);
        }
      }

      if (count != dynamic_reconfigure::ConfigTools::size(msg))
      {
        ROS_ERROR("RangeSensorConfig::__fromMessage__ called with an unexpected parameter.");
        ROS_ERROR("Booleans:");
        for (unsigned int i = 0; i < msg.bools.size(); i++)
          ROS_ERROR("  %s", msg.bools[i].name.c_str());
        ROS_ERROR("Integers:");
        for (unsigned int i = 0; i < msg.ints.size(); i++)
          ROS_ERROR("  %s", msg.ints[i].name.c_str());
        ROS_ERROR("Doubles:");
        for (unsigned int i = 0; i < msg.doubles.size(); i++)
          ROS_ERROR("  %s", msg.doubles[i].name.c_str());
        ROS_ERROR("Strings:");
        for (unsigned int i = 0; i < msg.strs.size(); i++)
          ROS_ERROR("  %s", msg.strs[i].name.c_str());
        // @todo Check that there are no duplicates. Make this error more
        // explicit.
        return false;
      }
      return true;
    }

    // This version of __toMessage__ is used during initialization of
    // statics when __getParamDescriptions__ can't be called yet.
    void __toMessage__(dynamic_reconfigure::Config &msg, const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__, const std::vector<AbstractGroupDescriptionConstPtr> &__group_descriptions__) const
    {
      dynamic_reconfigure::ConfigTools::clear(msg);
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); ++i)
        (*i)->toMessage(msg, *this);

      for (std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = __group_descriptions__.begin(); i != __group_descriptions__.end(); ++i)
      {
        if((*i)->id == 0)
        {
          (*i)->toMessage(msg, *this);
        }
      }
    }
    
    void __toMessage__(dynamic_reconfigure::Config &msg) const
    {
      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      const std::vector<AbstractGroupDescriptionConstPtr> &__group_descriptions__ = __getGroupDescriptions__();
      __toMessage__(msg, __param_descriptions__, __group_descriptions__);
    }
    
    void __toServer__(const ros::NodeHandle &nh) const
    {
      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); ++i)
        (*i)->toServer(nh, *this);
    }

    void __fromServer__(const ros::NodeHandle &nh)
    {
      static bool setup=false;

      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); ++i)
        (*i)->fromServer(nh, *this);

      const std::vector<AbstractGroupDescriptionConstPtr> &__group_descriptions__ = __getGroupDescriptions__();
      for (std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = __group_descriptions__.begin(); i != __group_descriptions__.end(); i++){
        if (!setup && (*i)->id == 0) {
          setup = true;
          boost::any n = boost::any(this);
          (*i)->setInitialState(n);
        }
      }
    }

    void __clamp__()
    {
      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      const RangeSensorConfig &__max__ = __getMax__();
      const RangeSensorConfig &__min__ = __getMin__();
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); ++i)
        (*i)->clamp(*this, __max__, __min__);
    }

    uint32_t __level__(const RangeSensorConfig &config) const
    {
      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      uint32_t level = 0;
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); ++i)
        (*i)->calcLevel(level, config, *this);
      return level;
    }
    
    static const dynamic_reconfigure::ConfigDescription &__getDescriptionMessage__();
    static const RangeSensorConfig &__getDefault__();
    static const RangeSensorConfig &__getMax__();
    static const RangeSensorConfig &__getMin__();
    static const std::vector<AbstractParamDescriptionConstPtr> &__getParamDescriptions__();
    static const std::vector<AbstractGroupDescriptionConstPtr> &__getGroupDescriptions__();
    
  private:
    static const RangeSensorConfigStatics *__get_statics__();
  };
  
  template <> // Max and min are ignored for strings.
  inline void RangeSensorConfig::ParamDescription<std::string>::clamp(RangeSensorConfig &config, const RangeSensorConfig &max, const RangeSensorConfig &min) const
  {
    return;
  }

  class RangeSensorConfigStatics
  {
    friend class RangeSensorConfig;
    
    RangeSensorConfigStatics()
    {
RangeSensorConfig::GroupDescription<RangeSensorConfig::DEFAULT, RangeSensorConfig> Default("Default", "", 0, 0, true, &RangeSensorConfig::groups);
//#line 280 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.laser_obstacle_color = 0;
//#line 280 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.laser_obstacle_color = 255;
//#line 280 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.laser_obstacle_color = 0;
//#line 280 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(RangeSensorConfig::AbstractParamDescriptionConstPtr(new RangeSensorConfig::ParamDescription<int>("laser_obstacle_color", "int", 0, "color of a pixel on an occupancy grid that should be regarded as an obstacle", "", &RangeSensorConfig::laser_obstacle_color)));
//#line 280 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(RangeSensorConfig::AbstractParamDescriptionConstPtr(new RangeSensorConfig::ParamDescription<int>("laser_obstacle_color", "int", 0, "color of a pixel on an occupancy grid that should be regarded as an obstacle", "", &RangeSensorConfig::laser_obstacle_color)));
//#line 280 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.laser_max_sensor_distance = 0.0;
//#line 280 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.laser_max_sensor_distance = 30.0;
//#line 280 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.laser_max_sensor_distance = 6.0;
//#line 280 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(RangeSensorConfig::AbstractParamDescriptionConstPtr(new RangeSensorConfig::ParamDescription<double>("laser_max_sensor_distance", "double", 0, "maximum sensing distance of the simulated laser range sensor", "", &RangeSensorConfig::laser_max_sensor_distance)));
//#line 280 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(RangeSensorConfig::AbstractParamDescriptionConstPtr(new RangeSensorConfig::ParamDescription<double>("laser_max_sensor_distance", "double", 0, "maximum sensing distance of the simulated laser range sensor", "", &RangeSensorConfig::laser_max_sensor_distance)));
//#line 280 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.laser_min_sensor_distance = 0.0;
//#line 280 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.laser_min_sensor_distance = 30.0;
//#line 280 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.laser_min_sensor_distance = 0.0;
//#line 280 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(RangeSensorConfig::AbstractParamDescriptionConstPtr(new RangeSensorConfig::ParamDescription<double>("laser_min_sensor_distance", "double", 0, "minimum sensing distance of the simulated laser range sensor", "", &RangeSensorConfig::laser_min_sensor_distance)));
//#line 280 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(RangeSensorConfig::AbstractParamDescriptionConstPtr(new RangeSensorConfig::ParamDescription<double>("laser_min_sensor_distance", "double", 0, "minimum sensing distance of the simulated laser range sensor", "", &RangeSensorConfig::laser_min_sensor_distance)));
//#line 280 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.laser_field_of_view = 0.0;
//#line 280 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.laser_field_of_view = 360.0;
//#line 280 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.laser_field_of_view = 90.0;
//#line 280 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(RangeSensorConfig::AbstractParamDescriptionConstPtr(new RangeSensorConfig::ParamDescription<double>("laser_field_of_view", "double", 0, "the simulated laser range sensors field of view (deg)", "", &RangeSensorConfig::laser_field_of_view)));
//#line 280 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(RangeSensorConfig::AbstractParamDescriptionConstPtr(new RangeSensorConfig::ParamDescription<double>("laser_field_of_view", "double", 0, "the simulated laser range sensors field of view (deg)", "", &RangeSensorConfig::laser_field_of_view)));
//#line 280 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.laser_angular_resolution = 0.01;
//#line 280 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.laser_angular_resolution = 360.0;
//#line 280 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.laser_angular_resolution = 0.5;
//#line 280 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(RangeSensorConfig::AbstractParamDescriptionConstPtr(new RangeSensorConfig::ParamDescription<double>("laser_angular_resolution", "double", 0, "angular resolution of the laser sensors field of view (deg)", "", &RangeSensorConfig::laser_angular_resolution)));
//#line 280 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(RangeSensorConfig::AbstractParamDescriptionConstPtr(new RangeSensorConfig::ParamDescription<double>("laser_angular_resolution", "double", 0, "angular resolution of the laser sensors field of view (deg)", "", &RangeSensorConfig::laser_angular_resolution)));
//#line 280 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.us_obstacle_color = 0;
//#line 280 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.us_obstacle_color = 255;
//#line 280 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.us_obstacle_color = 0;
//#line 280 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(RangeSensorConfig::AbstractParamDescriptionConstPtr(new RangeSensorConfig::ParamDescription<int>("us_obstacle_color", "int", 0, "color of a pixel on an occupancy grid that should be regarded as an obstacle", "", &RangeSensorConfig::us_obstacle_color)));
//#line 280 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(RangeSensorConfig::AbstractParamDescriptionConstPtr(new RangeSensorConfig::ParamDescription<int>("us_obstacle_color", "int", 0, "color of a pixel on an occupancy grid that should be regarded as an obstacle", "", &RangeSensorConfig::us_obstacle_color)));
//#line 280 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.us_max_sensor_distance = 0.0;
//#line 280 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.us_max_sensor_distance = 30.0;
//#line 280 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.us_max_sensor_distance = 2.7;
//#line 280 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(RangeSensorConfig::AbstractParamDescriptionConstPtr(new RangeSensorConfig::ParamDescription<double>("us_max_sensor_distance", "double", 0, "maximum sensing distance of the simulated us range sensor", "", &RangeSensorConfig::us_max_sensor_distance)));
//#line 280 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(RangeSensorConfig::AbstractParamDescriptionConstPtr(new RangeSensorConfig::ParamDescription<double>("us_max_sensor_distance", "double", 0, "maximum sensing distance of the simulated us range sensor", "", &RangeSensorConfig::us_max_sensor_distance)));
//#line 280 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.us_min_sensor_distance = 0.0;
//#line 280 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.us_min_sensor_distance = 30.0;
//#line 280 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.us_min_sensor_distance = 0.0;
//#line 280 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(RangeSensorConfig::AbstractParamDescriptionConstPtr(new RangeSensorConfig::ParamDescription<double>("us_min_sensor_distance", "double", 0, "minimum sensing distance of the simulated us range sensor", "", &RangeSensorConfig::us_min_sensor_distance)));
//#line 280 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(RangeSensorConfig::AbstractParamDescriptionConstPtr(new RangeSensorConfig::ParamDescription<double>("us_min_sensor_distance", "double", 0, "minimum sensing distance of the simulated us range sensor", "", &RangeSensorConfig::us_min_sensor_distance)));
//#line 280 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.us_field_of_view = 0.0;
//#line 280 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.us_field_of_view = 360.0;
//#line 280 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.us_field_of_view = 45.0;
//#line 280 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(RangeSensorConfig::AbstractParamDescriptionConstPtr(new RangeSensorConfig::ParamDescription<double>("us_field_of_view", "double", 0, "the simulated us range sensors field of view (deg)", "", &RangeSensorConfig::us_field_of_view)));
//#line 280 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(RangeSensorConfig::AbstractParamDescriptionConstPtr(new RangeSensorConfig::ParamDescription<double>("us_field_of_view", "double", 0, "the simulated us range sensors field of view (deg)", "", &RangeSensorConfig::us_field_of_view)));
//#line 280 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.us_angular_resolution = 0.01;
//#line 280 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.us_angular_resolution = 360.0;
//#line 280 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.us_angular_resolution = 0.5;
//#line 280 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(RangeSensorConfig::AbstractParamDescriptionConstPtr(new RangeSensorConfig::ParamDescription<double>("us_angular_resolution", "double", 0, "angular resolution of the us sensors field of view (deg)", "", &RangeSensorConfig::us_angular_resolution)));
//#line 280 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(RangeSensorConfig::AbstractParamDescriptionConstPtr(new RangeSensorConfig::ParamDescription<double>("us_angular_resolution", "double", 0, "angular resolution of the us sensors field of view (deg)", "", &RangeSensorConfig::us_angular_resolution)));
//#line 235 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.convertParams();
//#line 235 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __group_descriptions__.push_back(RangeSensorConfig::AbstractGroupDescriptionConstPtr(new RangeSensorConfig::GroupDescription<RangeSensorConfig::DEFAULT, RangeSensorConfig>(Default)));
//#line 353 "/opt/ros/indigo/share/dynamic_reconfigure/cmake/../templates/ConfigType.h.template"

      for (std::vector<RangeSensorConfig::AbstractGroupDescriptionConstPtr>::const_iterator i = __group_descriptions__.begin(); i != __group_descriptions__.end(); ++i)
      {
        __description_message__.groups.push_back(**i);
      }
      __max__.__toMessage__(__description_message__.max, __param_descriptions__, __group_descriptions__); 
      __min__.__toMessage__(__description_message__.min, __param_descriptions__, __group_descriptions__); 
      __default__.__toMessage__(__description_message__.dflt, __param_descriptions__, __group_descriptions__); 
    }
    std::vector<RangeSensorConfig::AbstractParamDescriptionConstPtr> __param_descriptions__;
    std::vector<RangeSensorConfig::AbstractGroupDescriptionConstPtr> __group_descriptions__;
    RangeSensorConfig __max__;
    RangeSensorConfig __min__;
    RangeSensorConfig __default__;
    dynamic_reconfigure::ConfigDescription __description_message__;

    static const RangeSensorConfigStatics *get_instance()
    {
      // Split this off in a separate function because I know that
      // instance will get initialized the first time get_instance is
      // called, and I am guaranteeing that get_instance gets called at
      // most once.
      static RangeSensorConfigStatics instance;
      return &instance;
    }
  };

  inline const dynamic_reconfigure::ConfigDescription &RangeSensorConfig::__getDescriptionMessage__() 
  {
    return __get_statics__()->__description_message__;
  }

  inline const RangeSensorConfig &RangeSensorConfig::__getDefault__()
  {
    return __get_statics__()->__default__;
  }
  
  inline const RangeSensorConfig &RangeSensorConfig::__getMax__()
  {
    return __get_statics__()->__max__;
  }
  
  inline const RangeSensorConfig &RangeSensorConfig::__getMin__()
  {
    return __get_statics__()->__min__;
  }
  
  inline const std::vector<RangeSensorConfig::AbstractParamDescriptionConstPtr> &RangeSensorConfig::__getParamDescriptions__()
  {
    return __get_statics__()->__param_descriptions__;
  }

  inline const std::vector<RangeSensorConfig::AbstractGroupDescriptionConstPtr> &RangeSensorConfig::__getGroupDescriptions__()
  {
    return __get_statics__()->__group_descriptions__;
  }

  inline const RangeSensorConfigStatics *RangeSensorConfig::__get_statics__()
  {
    const static RangeSensorConfigStatics *statics;
  
    if (statics) // Common case
      return statics;

    boost::mutex::scoped_lock lock(dynamic_reconfigure::__init_mutex__);

    if (statics) // In case we lost a race.
      return statics;

    statics = RangeSensorConfigStatics::get_instance();
    
    return statics;
  }


}

#endif // __RANGESENSORRECONFIGURATOR_H__
